import type { MenuItem, Restaurant } from './types';

export const mockRestaurants: Restaurant[] = [
  {
    id: 'r1',
    name: 'Sabores de Cabinda',
    imageUrl: 'https://picsum.photos/seed/r1/400/300',
    rating: 4.7,
    cuisine: 'Angolana',
    deliveryTimeMinutes: 25,
    deliveryFee: 500,
    description: 'Sabores autênticos de Cabinda, direto para a sua mesa.',
  },
  {
    id: 'r2',
    name: 'Marisqueira do Kinaxixe',
    imageUrl: 'https://picsum.photos/seed/r2/400/300',
    rating: 4.5,
    cuisine: 'Marisco',
    deliveryTimeMinutes: 35,
    deliveryFee: 700,
    description: 'Marisco fresco do dia, preparado à moda da casa.',
  },
  {
    id: 'r3',
    name: 'Pizza Talatona',
    imageUrl: 'https://picsum.photos/seed/r3/400/300',
    rating: 4.3,
    cuisine: 'Italiana',
    deliveryTimeMinutes: 30,
    deliveryFee: 600,
    description: 'Pizzas artesanais assadas em forno a lenha em Talatona.',
  },
  {
    id: 'r4',
    name: 'Burger Ingombota',
    imageUrl: 'https://picsum.photos/seed/r4/400/300',
    rating: 4.2,
    cuisine: 'Fast Food',
    deliveryTimeMinutes: 20,
    deliveryFee: 400,
    description: 'Hambúrgueres suculentos e batatas crocantes em Ingombota.',
  },
  {
    id: 'r5',
    name: 'Muxima Grill',
    imageUrl: 'https://picsum.photos/seed/r5/400/300',
    rating: 4.8,
    cuisine: 'Grelhados',
    deliveryTimeMinutes: 40,
    deliveryFee: 800,
    description: 'Grelhados na brasa com o sabor tradicional angolano.',
  },
  {
    id: 'r6',
    name: 'Sushi Luanda',
    imageUrl: 'https://picsum.photos/seed/r6/400/300',
    rating: 4.6,
    cuisine: 'Japonesa',
    deliveryTimeMinutes: 45,
    deliveryFee: 900,
    description: 'Sushi fresco e combinados japoneses no coração de Luanda.',
  },
  {
    id: 'r7',
    name: 'Moamba de Galinha Tradicional',
    imageUrl: 'https://picsum.photos/seed/r7/400/300',
    rating: 4.4,
    cuisine: 'Angolana',
    deliveryTimeMinutes: 35,
    deliveryFee: 650,
    description: 'Moamba de galinha tradicional, feita como em casa.',
  },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'r1-1',
    restaurantId: 'r1',
    name: 'Calulu de Peixe',
    description: 'Peixe seco cozinhado com quiabo, jinguba e óleo de palma.',
    price: 4500,
    imageUrl: 'https://picsum.photos/seed/r1-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r1-2',
    restaurantId: 'r1',
    name: 'Funge com Feijão',
    description: 'Funge de bombó acompanhado de feijão de óleo de palma.',
    price: 3200,
    imageUrl: 'https://picsum.photos/seed/r1-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r1-3',
    restaurantId: 'r1',
    name: 'Gindungo Frito',
    description: 'Entrada picante de pimenta gindungo frita.',
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/r1-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r1-4',
    restaurantId: 'r1',
    name: 'Kissangua',
    description: 'Bebida tradicional fermentada de milho.',
    price: 1000,
    imageUrl: 'https://picsum.photos/seed/r1-4/200/200',
    category: 'Bebidas',
  },
  {
    id: 'r2-1',
    restaurantId: 'r2',
    name: 'Camarão Grelhado',
    description: 'Camarão fresco grelhado com alho e limão.',
    price: 6500,
    imageUrl: 'https://picsum.photos/seed/r2-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r2-2',
    restaurantId: 'r2',
    name: 'Caranguejo à Moda da Casa',
    description: 'Caranguejo cozido no molho da casa.',
    price: 7200,
    imageUrl: 'https://picsum.photos/seed/r2-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r2-3',
    restaurantId: 'r2',
    name: 'Salada de Polvo',
    description: 'Polvo cozido com cebola, azeite e coentros.',
    price: 3800,
    imageUrl: 'https://picsum.photos/seed/r2-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r2-4',
    restaurantId: 'r2',
    name: 'Sumo de Maboque',
    description: 'Sumo natural de fruta maboque.',
    price: 1200,
    imageUrl: 'https://picsum.photos/seed/r2-4/200/200',
    category: 'Bebidas',
  },
  {
    id: 'r3-1',
    restaurantId: 'r3',
    name: 'Pizza Margherita',
    description: 'Molho de tomate, mozzarella e manjericão fresco.',
    price: 4000,
    imageUrl: 'https://picsum.photos/seed/r3-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r3-2',
    restaurantId: 'r3',
    name: 'Pizza Pepperoni',
    description: 'Molho de tomate, mozzarella e pepperoni.',
    price: 4800,
    imageUrl: 'https://picsum.photos/seed/r3-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r3-3',
    restaurantId: 'r3',
    name: 'Bruschetta',
    description: 'Pão tostado com tomate, alho e azeite.',
    price: 2000,
    imageUrl: 'https://picsum.photos/seed/r3-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r3-4',
    restaurantId: 'r3',
    name: 'Tiramisu',
    description: 'Sobremesa italiana com café e mascarpone.',
    price: 2500,
    imageUrl: 'https://picsum.photos/seed/r3-4/200/200',
    category: 'Sobremesas',
  },
  {
    id: 'r4-1',
    restaurantId: 'r4',
    name: 'Cheeseburger Clássico',
    description: 'Hambúrguer de carne, queijo cheddar, alface e tomate.',
    price: 3000,
    imageUrl: 'https://picsum.photos/seed/r4-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r4-2',
    restaurantId: 'r4',
    name: 'Burger Duplo Bacon',
    description: 'Duas carnes, bacon crocante e molho especial.',
    price: 3800,
    imageUrl: 'https://picsum.photos/seed/r4-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r4-3',
    restaurantId: 'r4',
    name: 'Batata Frita',
    description: 'Porção de batata frita crocante.',
    price: 1200,
    imageUrl: 'https://picsum.photos/seed/r4-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r4-4',
    restaurantId: 'r4',
    name: 'Milkshake de Chocolate',
    description: 'Milkshake cremoso de chocolate.',
    price: 1800,
    imageUrl: 'https://picsum.photos/seed/r4-4/200/200',
    category: 'Bebidas',
  },
  {
    id: 'r5-1',
    restaurantId: 'r5',
    name: 'Espetada de Frango',
    description: 'Espetada de frango grelhado com pimentos.',
    price: 4200,
    imageUrl: 'https://picsum.photos/seed/r5-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r5-2',
    restaurantId: 'r5',
    name: 'Costela de Porco Grelhada',
    description: 'Costela suína grelhada com molho barbecue.',
    price: 5200,
    imageUrl: 'https://picsum.photos/seed/r5-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r5-3',
    restaurantId: 'r5',
    name: 'Salada Mista',
    description: 'Alface, tomate, cebola e pepino.',
    price: 1500,
    imageUrl: 'https://picsum.photos/seed/r5-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r5-4',
    restaurantId: 'r5',
    name: 'Cerveja Cuca',
    description: 'Cerveja angolana gelada.',
    price: 1000,
    imageUrl: 'https://picsum.photos/seed/r5-4/200/200',
    category: 'Bebidas',
  },
  {
    id: 'r6-1',
    restaurantId: 'r6',
    name: 'Combo Sashimi',
    description: '12 peças variadas de sashimi fresco.',
    price: 7500,
    imageUrl: 'https://picsum.photos/seed/r6-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r6-2',
    restaurantId: 'r6',
    name: 'Uramaki Philadelphia',
    description: 'Salmão, queijo creme e pepino.',
    price: 5500,
    imageUrl: 'https://picsum.photos/seed/r6-2/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r6-3',
    restaurantId: 'r6',
    name: 'Edamame',
    description: 'Vagens de soja cozidas com sal marinho.',
    price: 1800,
    imageUrl: 'https://picsum.photos/seed/r6-3/200/200',
    category: 'Entradas',
  },
  {
    id: 'r6-4',
    restaurantId: 'r6',
    name: 'Chá Verde Gelado',
    description: 'Chá verde japonês servido gelado.',
    price: 1100,
    imageUrl: 'https://picsum.photos/seed/r6-4/200/200',
    category: 'Bebidas',
  },
  {
    id: 'r7-1',
    restaurantId: 'r7',
    name: 'Moamba de Galinha',
    description: 'Galinha cozida em molho de ginguba com quiabo.',
    price: 3800,
    imageUrl: 'https://picsum.photos/seed/r7-1/200/200',
    category: 'Pratos Principais',
  },
  {
    id: 'r7-2',
    restaurantId: 'r7',
    name: 'Cacimba de Peixe',
    description: 'Caldo tradicional de peixe com gengibre e alho.',
    price: 4200,
    imageUrl: 'https://picsum.photos/seed/r7-2/200/200',
    category: 'Pratos Principais',
  },
];
